name: Deploy to EC2 (No Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd manu-githubpractice-demo || git clone https://github.com/${{ github.repository }} && cd manu-githubpractice-demo
            git pull origin main
            npm install
            pkill node || true
            nohup node index.js > output.log 2>&1 &
